/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <linux/input.h>
/* Header for class org_honeynet_droidbotrecorder_input_injection_EventsInjector */

#ifndef _Included_org_honeynet_droidbotrecorder_input_injection_EventsInjector
#define _Included_org_honeynet_droidbotrecorder_input_injection_EventsInjector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    intEnableDebug
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_intEnableDebug
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    scanDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_scanDevices
        (JNIEnv *, jclass);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    openDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_openDevice
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    closeDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_closeDevice
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    getDevicePath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_getDevicePath
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    getDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_getDeviceName
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    pollDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_pollDevice
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_getType
        (JNIEnv *, jclass);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    getCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_getCode
        (JNIEnv *, jclass);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    getValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_getValue
        (JNIEnv *, jclass);

/*
 * Class:     org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method:    injectEvent
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_injectEvent
        (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class: org_honeynet_droidbotrecorder_input_injection_EventsInjector
 * Method: readEvent
 * Signature (I)I
 */
JNIEXPORT jintArray JNICALL Java_org_honeynet_droidbotrecorder_input_injection_EventsInjector_readEvent
        (JNIEnv *, jclass,  jint );

struct uinput_event {
    struct timeval time;
    uint16_t type;
    uint16_t code;
    uint32_t value;
};


#ifdef __cplusplus
}
#endif
#endif
